// SPOSOBI VIVODA ALERT CONFIRM PROMPT
// INTERPOLACIYU LEGKO DELAT S BEKTIKAMI (``) VNACALE I VSEREDINE STAVIM ZNAK DOLLAR I OTKRAVAEM SKOBKI
// V JS ESLİ ODNO ROVNO (=) TO ETO PRİSVAİVANİE 
// ESLİ 2 RAVNO (==) TO ETO SRAVNENİE
// ESLİ 3 RAVNO (===) TO ETO CETKOE SRAVNENİE T.E VSE SRAVNİVAETSA STROGOE SRAVNENIE CİSLOVOY Lİ İLİ STROCNİY TİP
// (2 * 4 = 8) (2 * 4 = "8")
// SUWESTVUYUT LOGICESKIE OPERATORI (I) i (ILI)
// OPERATOR I ZAPISIVAETSA KAK 2 AMPERSANTA (&&)
// OPERATOR ILI ZAPISIVAETSA KAK 2 VERTIKALNIE CERTOCKI (||)
// OPERATOR I VOZVRAWAET TRUE KOGDA VSE PRAVDIVO
// OPERATOR ILI (||) KOGDA XOTABI ODIN IZ ZNACENIY PRAVDIVIY ILI ETOT ILI TOT
// VOSKLICATELNIY ZNAK ETO (OTRICANIE !) ON STAVIT LUBOE ZNACENIE V OBRATNOE ESLI TRUE TO ! TRUE BUDET FALSE
// operator continue prerivaet cikl naprimer nam nujno 1234 continue (3) to budet 124!



//                         (( VOPROSI ))
// ZACEM POSLE PROMP V SKOBKA STAVIT " " PUSTIE KAVICKI DLA CEGO TAK I NE PONAL???